"""
Increase length of columns in Game model

Revision ID: 2b9439dd6872
Revises: 34508e96380b
Create Date: 2024-06-26 22:17:07.937057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9439dd6872'
down_revision = '34508e96380b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('developer',
               existing_type=sa.String(length=100),
               type_=sa.String(length=255),  # Increase the length to 255 characters
               existing_nullable=True)  # Handle existing NULL values if necessary



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('developer',
               existing_type=sa.String(length=255),
               type_=sa.String(length=100),  # Downgrade the length back to 100 characters if needed
               existing_nullable=True)  # Ensure it handles existing NULL values correctly

    # ### end Alembic commands ###
