"""empty message

Revision ID: 34508e96380b
Revises: 6beb8c4c8278
Create Date: 2024-06-26 21:28:32.850750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34508e96380b'
down_revision = '6beb8c4c8278'
branch_labels = None
depends_on = None


def upgrade():
    # Add a new column 'new_rating' and update it with converted data
    op.add_column('game', sa.Column('new_rating', sa.Integer()))

    # Update 'new_rating' with converted data from 'rating'
    op.execute('UPDATE game SET new_rating = rating::integer')

    # Drop the old 'rating' column
    op.drop_column('game', 'rating')

    # Rename 'new_rating' back to 'rating'
    op.alter_column('game', 'new_rating', new_column_name='rating')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('profile_image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_unique_constraint('game_title_key', ['title'])
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('developer',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('platform',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('art',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
