"""empty message

Revision ID: 7ccd169202c0
Revises: 2b9439dd6872
Create Date: 2024-06-26 23:31:11.813978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccd169202c0'
down_revision = '2b9439dd6872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('art',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_constraint('game_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_unique_constraint('game_title_key', ['title'])
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('art',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
